/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2015-10-11 13:17:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class inicio_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>Farmacia Ya</title>\r\n");
      out.write("\t<!--  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">  -->\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/estilos.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function validacion() {\r\n");
      out.write("\tnombre = document.getElementById(\"nombre\").value;\r\n");
      out.write("\tif( nombre == null || nombre.length == 0 || /^\\s+$/.test(nombre) ) {\r\n");
      out.write("\t\talert('[ERROR] El campo Nombre debe tener un valor de.');\r\n");
      out.write("\t  \treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tapellido = document.getElementById(\"apellido\").value;\r\n");
      out.write("\tif( apellido == null || apellido.length == 0 || /^\\s+$/.test(apellido) ) {\r\n");
      out.write("\t\talert('[ERROR] El campo Apellido debe tener un valor de.');\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tapellido = document.getElementById(\"correo\").value;\r\n");
      out.write("\tif( apellido == null || apellido.length == 0 || /^\\s+$/.test(apellido) ) {\r\n");
      out.write("\t\talert('[ERROR] El campo Correo debe tener un valor de.');\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tapellido = document.getElementById(\"direccion\").value;\r\n");
      out.write("\tif( apellido == null || apellido.length == 0 || /^\\s+$/.test(apellido) ) {\r\n");
      out.write("\t\talert('[ERROR] El campo Dirección debe tener un valor de.');\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tapellido = document.getElementById(\"password\").value;\r\n");
      out.write("\tif( apellido == null || apellido.length == 0 || /^\\s+$/.test(apellido) ) {\r\n");
      out.write("\t\talert('[ERROR] El campo Contraseña debe tener un valor de.');\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function newPage(url){\r\n");
      out.write("\twindow.location.href = url;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");

//allow access only if session exists
String user = null;
if(session.getAttribute("user") != null){
	response.sendRedirect("busqueda.jsp");
}

      out.write("\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<nav class=\"navbar navbar-inverse navbar-static-top\" role=\"navigation\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navegacion-isf3\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">Desplegar / Ocultar Menu</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"navbar-brand\">FarmaciaYa.com</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- MENU Prueba -->\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"navegacion-isf3\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"inicio.jsp\">Inicio</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Mis Calificaciones</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<form action=\"LoginServlet\" method=\"post\" class=\"navbar-form navbar-right\" role=\"loggin\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"user\" class=\"form-control\" placeholder=\"Correo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" name=\"pwd\" class=\"form-control\" placeholder=\"Contraseña\">\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-ok\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\tIniciar Sessión\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font color=red>");

							    if(null!=request.getAttribute("errorMessage"))
							    {
							        out.println(request.getAttribute("errorMessage"));
							    }
							
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"recuperar.jsp\">Olvido su contraseña?</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\t<section class=\"jumbotron jumbotron-inicio\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-6 hidden-xs hidden-sm\">\r\n");
      out.write("\t\t\t\t\t<h1 class=\"titulo-inicio\">Farmacia Ya</h1>\r\n");
      out.write("\t\t\t\t\t<p>Bienvenido a FarmaciaYa el sitio por excelencia</p>\r\n");
      out.write("\t\t\t\t\t<p>para pedir productos farmacéuticos.</p>\r\n");
      out.write("\t\t\t\t\t<p>Más de 250 Farmacias disponibles</p>\r\n");
      out.write("\t\t\t\t\t<p>24/7</p>\r\n");
      out.write("\t\t\t\t\t<p><a href=\"#\" class=\"btn btn-primary btn-lg\">Leer mas</a></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-13\">\r\n");
      out.write("\t\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<form action=\"UsuarioServlet\" method=\"post\" onsubmit=\"return validacion()\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"input-group-addon\">Nombre:</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"nombre\" name=\"nombre\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"input-group-addon\">Apellido:</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"apellido\" name=\"apellido\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"input-group-addon\">Dirección:</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"direccion\" name=\"direccion\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"input-group-addon\">Correo:</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"correo\" name=\"correo\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"input-group-addon\">Contraseña:</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" id=\"password\" name=\"password\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" name=\"Submit\" class=\"btn btn-success\"><span class=\"glyphicon glyphicon-ok\"></span> Confirmar</button>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t<footer class=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-6\">\r\n");
      out.write("\t\t\t\t\t<p>Ingeniería de Software III</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-13\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-inline text-right\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Inicio</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Mis Calificaciones</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Contacto</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"js/jquery.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
