INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (1, 'Efectivo', 'Efectivo', 1);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (2, 'Efectivo', 'Efectivo', 12);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (3, 'Efectivo', 'Efectivo', 2);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (4, 'Efectivo', 'Efectivo', 4);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (5, 'Efectivo', 'Efectivo', 5);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (6, 'Efectivo', 'Efectivo', 6);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (7, 'Efectivo', 'Efectivo', 7);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (8, 'Efectivo', 'Efectivo', 8);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (9, 'Efectivo', 'Efectivo', 9);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (10, 'Efectivo', 'Efectivo', 10);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (11, 'Efectivo', 'Efectivo', 11);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (12, 'Efectivo', 'Efectivo', 13);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (13, 'Efectivo', 'Efectivo', 14);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (14, 'Efectivo', 'Efectivo', 3);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (15, 'Efectivo', 'Efectivo', 15);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (16, 'Efectivo', 'Efectivo', 16);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (17, 'Efectivo', 'Efectivo', 17);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (18, 'Efectivo', 'Efectivo', 18);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (19, 'Efectivo', 'Efectivo', 19);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (20, 'Efectivo', 'Efectivo', 20);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (21, 'Efectivo', 'Efectivo', 21);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (22, 'Efectivo', 'Efectivo', 22);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (23, 'Efectivo', 'Efectivo', 23);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (24, 'Efectivo', 'Efectivo', 24);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (25, 'Efectivo', 'Efectivo', 25);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (26, 'Efectivo', 'Efectivo', 26);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (27, 'Efectivo', 'Efectivo', 27);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (28, 'Efectivo', 'Efectivo', 28);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (29, 'Efectivo', 'Efectivo', 29);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (30, 'Efectivo', 'Efectivo', 30);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (31, 'Efectivo', 'Efectivo', 31);

#otro metodo

INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (32, 'Todas las Tarjetas', 'Todas las Tarjetas', 1);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (33, 'Todas las Tarjetas', 'Todas las Tarjetas', 12);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (34, 'Todas las Tarjetas', 'Todas las Tarjetas', 2);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (35, 'Todas las Tarjetas', 'Todas las Tarjetas', 4);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (36, 'Todas las Tarjetas', 'Todas las Tarjetas', 5);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (37, 'Todas las Tarjetas', 'Todas las Tarjetas', 6);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (38, 'Todas las Tarjetas', 'Todas las Tarjetas', 7);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (39, 'Todas las Tarjetas', 'Todas las Tarjetas', 8);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (40, 'Todas las Tarjetas', 'Todas las Tarjetas', 9);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (41, 'Todas las Tarjetas', 'Todas las Tarjetas', 10);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (42, 'Todas las Tarjetas', 'Todas las Tarjetas', 11);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (43, 'Todas las Tarjetas', 'Todas las Tarjetas', 13);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (44, 'Todas las Tarjetas', 'Todas las Tarjetas', 14);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (45, 'Todas las Tarjetas', 'Todas las Tarjetas', 3);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (46, 'Todas las Tarjetas', 'Todas las Tarjetas', 15);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (47, 'Todas las Tarjetas', 'Todas las Tarjetas', 16);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (48, 'Todas las Tarjetas', 'Todas las Tarjetas', 17);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (49, 'Todas las Tarjetas', 'Todas las Tarjetas', 18);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (50, 'Todas las Tarjetas', 'Todas las Tarjetas', 19);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (51, 'Todas las Tarjetas', 'Todas las Tarjetas', 20);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (52, 'Todas las Tarjetas', 'Todas las Tarjetas', 21);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (53, 'Todas las Tarjetas', 'Todas las Tarjetas', 22);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (54, 'Todas las Tarjetas', 'Todas las Tarjetas', 23);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (55, 'Todas las Tarjetas', 'Todas las Tarjetas', 24);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (56, 'Todas las Tarjetas', 'Todas las Tarjetas', 25);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (57, 'Todas las Tarjetas', 'Todas las Tarjetas', 26);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (58, 'Todas las Tarjetas', 'Todas las Tarjetas', 27);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (59, 'Todas las Tarjetas', 'Todas las Tarjetas', 28);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (60, 'Todas las Tarjetas', 'Todas las Tarjetas', 29);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (61, 'Todas las Tarjetas', 'Todas las Tarjetas', 30);
INSERT INTO far_t_forma_pago(id, descripcion, nombre, forma_de_pago_fk)    VALUES (62, 'Todas las Tarjetas', 'Todas las Tarjetas', 31);